# Generated by Django 2.0.6 on 2020-11-05 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='type',
            table='type',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AlterModelTable(
            name='writings',
            table='writings',
        ),
    ]
