# Generated by Django 2.0.6 on 2020-11-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_auto_20201105_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='writings',
            name='cate_duiying_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
