# Generated by Django 2.0.6 on 2020-11-05 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0003_writings_cate_duiying_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writings',
            name='cate_duiying_id',
        ),
    ]
